let list = [
    { code: 7, name: "中国(China)" },
    { code: 4171, name: "中国香港(China HongKong)" },
    { code: 4170, name: "中国台湾(China Taiwan)" },
    { code: 10, name: "阿富汗(Afghanistan)" },
    { code: 27, name: "奥兰群岛(Aland lslands)" },
    { code: 8, name: "阿尔巴尼亚(Albania)" },
    { code: 9, name: "阿尔及利亚(Algeria)" },
    { code: 141, name: "美属萨摩亚(American Samoa)" },
    { code: 21, name: "安道尔(Andorra)" },
    { code: 22, name: "安哥拉(Angola)" },
    { code: 23, name: "安圭拉(Anguilla)" },
    { code: 156, name: "南极洲(Antarctica)" },
    { code: 24, name: "安提瓜岛和巴布达(Antigua and Barbuda)" },
    { code: 11, name: "阿根廷(Argentina)" },
    { code: 229, name: "亚美尼亚(Armenia)" },
    { code: 13, name: "阿鲁巴(Aruba)" },
    { code: 16, name: "阿森松岛(Ascension&nbsp;Island)" },
    { code: 25, name: "澳大利亚(Australia)" },
    { code: 26, name: "奥地利(Austria)" },
    { code: 15, name: "阿塞拜疆(Azerbaijan)" },
    { code: 30, name: "巴哈马(Bahamas)" },
    { code: 34, name: "巴林(Bahrain)" },
    { code: 145, name: "孟加拉(Bangladesh)" },
    { code: 28, name: "巴巴多斯岛(Barbados)" },
    { code: 42, name: "比利时(Belgium)" },
    { code: 49, name: "伯利兹(Belize)" },
    { code: 41, name: "贝宁(Benin)" },
    { code: 38, name: "百慕大(Bermuda)" },
    { code: 50, name: "不丹(Bhutan)" },
    { code: 46, name: "玻利维亚(Bolivia)" },
    { code: 47, name: "波斯尼亚和黑塞哥维那(Bosnia&nbsp;and&nbsp;Herzegovina)" },
    { code: 48, name: "博茨瓦纳(Botswana)" },
    { code: 53, name: "布韦岛(Bouvet&nbsp;Island)" },
    { code: 36, name: "巴西(Brazil)" },
];
export default list;